services:

  react:
    image: node:20.14.0-alpine3.19
    restart: always
    command: sh -c 'npm i && npm run dev'
    working_dir: /app
    volumes:
      - ./react:/app
    ports:
      - 3000:3000
