services:

  react:
    image: node:20.14.0-alpine3.19
    restart: always
    command: sh -c 'npm i && npm run dev'
    working_dir: /app
    volumes:
      - ./react:/app
    ports:
      - 3000:3000

  rails:
    build: ./rails
    restart: always
    environment:
      - RAILS_ENV=development
      - APP_DATABASE_PASSWORD=LryFLHCi8eBE2j47
      - RAILS_MAX_DB_CONNECTIONS=5
      - REDIS_URL=redis://redis:6379/1
      - BUNDLE_PATH=vendor/bundle
    volumes:
      - ./rails:/rails
    depends_on:
      - postgres
      - redis
    ports:
      - 3001:3000

  postgres:
    image: postgres:16.3
    environment:
      - POSTGRES_DB=rails
      - POSTGRES_USER=rails
      - POSTGRES_PASSWORD=LryFLHCi8eBE2j47
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  adminer:
    image: adminer:4.8.1
    restart: always
    depends_on:
      - postgres
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
      - ADMINER_DEFAULT_USER=rails
      - ADMINER_DEFAULT_PASSWORD=LryFLHCi8eBE2j47
      - ADMINER_DEFAULT_TYPE=postgresql
      - ADMINER_DEFAULT_PORT=5432
      - ADMINER_DEFAULT_DB=rails
    ports:
      - 8082:8080

  redis:
    image: redis:7.2.3-alpine
    volumes:
      - ./redis/data:/data
    ports:
      - 6379:6379